### ISSUE TITLE
How can I create a (9.1 Generic lineation (1st option) black arrow )

### ISSUE THREAD

**Issue by Charmatzis** [rclark/geocarto#4]
Hi,
You have done a excellent job!!!!!
I have one problem, I cannot find the code 9.1 which is a Generic lineation (1st option) and it's symbol is a black arrow.

Regards,
Christos.

**Comment by rclark** [comment]
Hi Christos! I believe that 9.1 is part of the [structure-points.mss file](https://github.com/rclark/geocarto/blob/3946957374810f15c168844c798f92c49f2bd5b1/structure-points.mss). The [svg is here](https://github.com/rclark/geocarto/blob/3946957374810f15c168844c798f92c49f2bd5b1/svg/9.1.svg).

**Comment by Charmatzis** [comment]
You're right!!!!
One more question..... why the SVG's have so large width and height? e.g. width="612px" height="792px"

**Comment by rclark** [comment]
I think this is just fallout from the way I exported them (using Adobe Illustrator). Nothing intentional really.
